# Generated by Django 4.2.7 on 2023-12-24 13:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleReaction',
            new_name='Reaction',
        ),
    ]
