# Generated by Django 4.2.7 on 2023-11-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='reactions',
            field=models.ManyToManyField(to='app.reaction'),
        ),
        migrations.AddField(
            model_name='question',
            name='reactions',
            field=models.ManyToManyField(to='app.reaction'),
        ),
    ]
